### ISSUE TITLE
Minecraft Launching

### ISSUE THREAD

**Issue by ccatears** [ChaoticTrials/SimplyTools#2]
Hello,

When I download this mod and add it into my mod library, the game starts up for a second and immediately closes. I tried downloading all the other mods in the description to work with it, but it still doesn't load. (The game being opening to the home screen, not the launcher or a particular save).

Thanks!:D

**Comment by MelanX** [comment]
Next time, please consider using one of the templates to provide the needed information:
![image](https://user-images.githubusercontent.com/26039509/174828557-e40ff2d4-ea0d-4b56-b439-bda24dab64c9.png)

**Comment by ccatears** [comment]
Hi,

Sorry I've never used this before and I didn't know if it was a bug or something just to do with me, so I didn't want to list it as such! So sorry!!

Minecraft 1.19
LibX 1.19-4.0.4
Simply Tools 1.19-1.0.2
Forge 1.19-41.0.4
Latest Log https://gist.github.com/ccatears/428a65192e5a5d3227a62f251849f78e

I'm not sure if the Latest Log thing is right, as I use the Forge Launcher, not a specific mod pack in CurseForge, so I got that from the logs labelled as latest.

Again, so sorry for any inconvenience!

**Comment by MelanX** [comment]
No problem! 
And it seems that you have an outdated Forge version. This mod version of Simply Tools requires at least `41.0.35`. Try to update.
If it still happens, tell me. Otherwise, you can close this issue.

And don't worry about the mistake, you learn from it for next time :)

**Comment by ccatears** [comment]
Thank you!
