### ISSUE TITLE
Exit Code -1 with "Reference{null=air} when starting game.

### ISSUE THREAD

**Issue by WreckItRa1ph** [ChaoticTrials/SimplyTools#3]
### Minecraft version

1.19.1

### LibX version

1.19.1-4.1.2

### Simply Tools version

1.19.1-1.1.0

### Forge version

42.0.1

### The latest.log file

https://pastebin.com/p7jhphz8

### Issue description

When trying to run the game with the most recent versions of Simply Tools and LibX, the game crashes and is throwing "Exit code -1" and "Reference{Null=air}".

**Comment by MelanX** [comment]
Can't reproduce with only Simply Tools 1.19.1-1.1.0 and LibX 1.19.1-4.1.2 on Forge 42.0.1. 
![image](https://user-images.githubusercontent.com/26039509/181924563-5947c893-7312-4ca8-95f7-cd5024913e86.png)
Needs to be another mod.
