### ISSUE TITLE
How do I repair your hammers?

### ISSUE THREAD

**Issue by therealeric** [ChaoticTrials/SimplyTools#5]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.6

### Simply Tools version

1.19.1-1.1.14

### Forge version

43.1.24

### The latest.log file

there is no log

### Issue description

How do I repair your hammers?

I also have Morevanillalib and Morevanillatools installed.

I have tried to repair with an anvil,  I cannot romove the repaired tool.
The grindstone does nothing.
Also I tried repairing in the Crafting Grid, also nothing.

Please teach me how to repair your tools.  I really like using them, but they do get expensive when you can't repair them.

**Comment by MelanX** [comment]
Can be repaired like normal items now :) If you can't figure out which item the repair item is, you could install [MoreVanillaLib](https://modrinth.com/mod/morevanillalib) to have additional info and features for the tools.
