### ISSUE TITLE
Make it for fabric

### ISSUE THREAD

**Issue by Majorkrabbe** [ChaoticTrials/SimplyTools#8]
### Describe your idea

Well.... Ehm.... Make it for fabric to.... :-)

**Comment by MelanX** [comment]
Well… ehm… no… :-)

**Comment by Majorkrabbe** [comment]
That sucks.

**Comment by MelanX** [comment]
Just use the existing alternatives for Fabric. Vanilla Hammers for fabric exists. I just ported it to Forge and combined it with another mod to make Simply Tools.
