### ISSUE TITLE
Tools will only break one block regardless of enchant level and not sneaking

### ISSUE THREAD

**Issue by larius11** [ChaoticTrials/SimplyTools#9]
### Minecraft version

None

### LibX version

5.0.5

### Simply Tools version

2.0.0

### MoreVanillaLib version

5.0.1

### Forge version

47.1.0

### The latest.log file

N/A (Logs don't show an error or warning when I mine)

### Issue description

The animation for the 3x3 area looks correct but when it ends only the middle block breaks. I've tried with every Excavator and Hammer at all enchanted levels. I've checked my configuration and I am not sneaking. 

I tried updating to the latest SimplyTools hoping for a fix but that version requires me to use a higher version of Forge which breaks other mods. I tried just using SimplyTools latest version in a new world by itself and I am seeing the same issue. The Forge version I used in that case was 47.1.44, the other mods (LibX, MoreVanillaLib) stayed the same.

### Steps to reproduce

1. Install the above-mentioned versions of Forge and the mods
2. Load into a creative world
3. Utilize either hammer or excavator at the appropriate level (Ii.e. Obsidian)

**Comment by MelanX** [comment]
Already fixed here: https://github.com/MelanX/SimplyTools/commit/15225940638c03503fb1476294d5eeae53b68ba5 (2.0.1)

**Comment by larius11** [comment]
~~It does not seem fixed. I upgraded to forge 47.1.42 and version 2.0.1 of the mod and I still can only mine one block at a time no matter what~~

My apologies, it seems another mod is messing with it, I did a fresh install of forge and it's working.

**Comment by MelanX** [comment]
~~Did you try basic combinations like iron hammer on stone, or anything special like obsidian hammer on stone?~~

**Comment by MelanX** [comment]
If you find out which mod is messing up, you could create a new issue for that and I try to find the problem.

**Comment by larius11** [comment]
Found it! It's a tree-chopping mod, it messes with how blocks break, I didn't think it would affect things like stone but apparently, it does. Here's the link to the file of the mod: https://www.curseforge.com/minecraft/mc-mods/treechop/files/4685647

For now, I'm gonna try to find another tree-chopping mod that works, this one is kinda basic anyways. Thank you for the quick replies and for your work, I love this mod!
